# Generated by Django 2.2 on 2019-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
