# Generated by Django 2.2 on 2019-05-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM_web', '0002_auto_20190523_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
