# Generated by Django 2.2 on 2019-05-27 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PM_web', '0004_team_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_information',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team_information',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_information',
            name='type',
            field=models.CharField(choices=[('1', '研发团队'), ('2', '测试团队'), ('3', '项目团队'), ('4', '产品团队'), ('5', '架构团队'), ('6', '售前团队'), ('7', '驻地团队'), ('8', '运管团队'), ('9', '运维团队'), ('0', '其他团队')], default='3', max_length=32),
        ),
        migrations.AddField(
            model_name='team_information',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
