# Generated by Django 2.2 on 2019-05-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM_web', '0006_operator_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator_info',
            name='province',
            field=models.CharField(choices=[('京', '北京市'), ('津', '天津市'), ('冀', '河北省'), ('晋', '山西省'), ('内蒙古', '内蒙古自治区'), ('辽', '辽宁省'), ('吉', '吉林省'), ('黑', '黑龙江省'), ('沪', '上海市'), ('苏', '江苏省'), ('浙', '浙江省'), ('皖', '安徽省'), ('闽', '福建省'), ('赣', '江西省'), ('鲁', '山东省'), ('豫', '河南省'), ('鄂', '湖北省'), ('湘', '湖南省'), ('粤', '广东省'), ('桂', '广西壮族自治区'), ('琼', '海南省'), ('川', '四川省'), ('贵', '贵州省'), ('滇', '云南省'), ('渝', '重庆市'), ('藏', '西藏自治区'), ('陕', '陕西省'), ('甘', '甘肃省'), ('青', '青海省'), ('宁', '宁夏回族自治区'), ('新', '新疆维吾尔自治区'), ('港', '香港特别行政区'), ('澳', '澳门特别行政区'), ('台', '台湾省')], default='沪', max_length=32, verbose_name='运营商所属省份'),
        ),
    ]
