# Generated by Django 2.2 on 2019-05-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PM_web', '0007_auto_20190528_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operator_info',
            new_name='Operator',
        ),
        migrations.CreateModel(
            name='station_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='驻地id', max_length=20)),
                ('station_name', models.CharField(help_text='驻地名称', max_length=52)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('station_manager', models.ForeignKey(help_text='驻地总经理', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
